### ISSUE TITLE
file_upload

### ISSUE THREAD

**Issue by thanesh56** [nikhilgeo/threadfix-api-wrapper#1]
Hi Nikhil, 
can you please help me related to which  file you uploaded in threadfix and there extension.
Thank you

**Comment by nikhilgeo** [comment]
@thanesh56,
From the code the uploaded file name is supplied as command line parameter and the file extension is .json.

**Comment by thanesh56** [comment]
Actually .json is depricated and currently .threadfix is supported, today I found this from  threadfix documentation.
now, i am having another issue, i want to upload another file again using same id, then i got Error: threadfix is already uploaded.
can you please suggest me any solution for this

**Comment by nikhilgeo** [comment]
Apologies, this was an old test script, I wrote long back for some automation and its no more maintained please feel free to fork the project.

**Comment by thanesh56** [comment]
Ya, Thank you for response and i resolved the above error.
